### ISSUE TITLE
Link to Karma plugin

### ISSUE THREAD

**Issue by alexweber** [substantial/sinon-stub-promise#10]
In case anyone's interested I've written a Karma plugin for this great little package: https://github.com/alexweber/karma-sinon-stub-promise

Would be nice if maintainers linked to it in README... :)

Thanks!

**Comment by astephenb** [comment]
Can you explain this plugin? We use `sinon-stub-promise` with karma without a plugin. 

I'm just curious.

**Comment by alexweber** [comment]
@astephenb I guess the main point is wrapping `sinon-stub-promise` in a proper Karma plugin so it can be added to frameworks & plugins as usual and not require you to manually add anything to `files:[]` for it to work... presumably that's how you're using it?

**Comment by astephenb** [comment]
Cool. Go ahead and make  PR, I can merge when I get a chance.

**Comment by alexweber** [comment]
:+1: Thanks!
